require('dotenv').config(); 
const express = require('express');
const path = require('path');
const { GoogleGenerativeAI } = require('@google/generative-ai');

const app = express();
app.use(express.json());

// Frontend static files ko serve karne ke liye
app.use(express.static(path.join(__dirname, 'public')));

// CORS Headers Setup
app.use((req, res, next) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    
    if (req.method === 'OPTIONS') {
        return res.sendStatus(200);
    }
    next();
});

// Process.env se secure key read karein
const aiEngine = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

app.post('/api/save-plan', async (req, res) => {
    const { goal, timeShift, hours, subjects } = req.body;
    let aiResponseText = "";
    
    try {
        const model = aiEngine.getGenerativeModel({ model: "gemini-pro" });
        const aiPrompt = `Create a custom study schedule for Goal: ${goal || "General"}, Hours: ${hours || 5}, Subjects: ${JSON.stringify(subjects || [])}, Peak: ${timeShift || "Morning"}. Format as plain text day breakdown without asterisks.`;

        const aiResult = await model.generateContent(aiPrompt);
        aiResponseText = aiResult.response.text();

        return res.status(200).json({ 
            success: true, 
            message: "Schedule generated by Gemini successfully!",
            schedule: aiResponseText 
        });

    } catch (aiError) {
        console.error("Gemini AI API Error, executing fallback:", aiError.message);
        aiResponseText = `[Smart Local Timetable - Network Fallback Mode]\nFocus Goal: ${goal}\nTotal Study Window: ${hours} Hours\nPeak Energy State: ${timeShift}\nTarget Subjects: ${JSON.stringify(subjects || [])}\n\nPlan structured successfully!`;
        
        return res.status(200).json({ 
            success: true, 
            message: "Fallback Schedule Activated",
            schedule: aiResponseText 
        });
    }
});
// Express 5 strictly compatible catch-all fallback
app.use((req, res) => {
    res.sendFile(path.join(__dirname, 'public', 'index.html'));
});
// Universal Cloud port binding
const PORT = process.env.PORT || 8080;
app.listen(PORT, '0.0.0.0', () => {
    console.log(`Backend Server Running on port: ${PORT}`);
});